# Generated by Django 2.0 on 2018-01-04 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriber_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='username',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
