# Generated by Django 2.0 on 2018-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20180104_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
