# Generated by Django 2.0 on 2018-01-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_subscriber_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='username',
        ),
    ]
